require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'
    - 'Rakefile'
    - 'config.ru'
    - 'Gemfile'

Rails/HelperInstanceVariable:
  Exclude:
    - 'app/helpers/layout_helper.rb'

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Rails/FilePath:
  Enabled: false
